### ISSUE TITLE
Add pre-/post-release checklist to docs

### ISSUE THREAD

**Issue by sedelmeyer** [sedelmeyer/cc-pyscript#8]
- [ ] Add to docs/about.rst
- [ ] include steps sample repo
    - Generate template for "sample-repo"
    - update "sample-repo" readme
    - run "sample-repo" tox
    - render "sample-repo" docs
    - push sample repo to develop to ensure build passes
    - merge and push master
    - add new version tag and push master
    - update gh-pages with updated html content
- [ ] include steps main repo
    - update changelog
    - run tox
    - render docs
    - push to develop to ensure build passes
    - merge and push master
    - add new version tag and push master
    - update gh-pages with new html content
    - checkout develop
